# Generated by Django 3.0.2 on 2020-02-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20200201_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='number',
            new_name='call_number',
        ),
    ]
