# Generated by Django 3.0.2 on 2020-02-12 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20200201_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Запит', 'verbose_name_plural': 'Запити на фотосесію'},
        ),
        migrations.AddField(
            model_name='subscriber',
            name='message',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
