# Generated by Django 3.0.2 on 2020-02-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20200212_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='message',
        ),
    ]
