# Generated by Django 3.0.2 on 2020-02-12 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_remove_subscriber_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='message',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='Message'),
            preserve_default=False,
        ),
    ]
