# Generated by Django 3.0.2 on 2020-02-12 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_subscriber_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=128, verbose_name='Event Date'),
            preserve_default=False,
        ),
    ]
