# Generated by Django 3.0.2 on 2020-02-12 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_subscriber_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='timemessage',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=128, verbose_name='Час відправки повідомлення'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='event_date',
            field=models.CharField(max_length=128, verbose_name='Час та дата фотосесії'),
        ),
    ]
