# Generated by Django 3.0.2 on 2020-02-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20200212_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='timemessage',
        ),
    ]
